version: "3"

services:
  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      PORT: "8081"
      GRPC_TRACE: all
      GRPC_VERBOSITY: DEBUG

  playlist-service:
    build:
      context: .
      dockerfile: services/playlist-service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      GRPC_TRACE: all
      GRPC_VERBOSITY: DEBUG

  gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      GRPC_TRACE: all
      GRPC_VERBOSITY: DEBUG